export const colors = {
  lightMode: {
    danger: "hsl(353, 78%, 47%)",
    dark1: "",
    dark2: "",
    dark3: "",
    dark4: "",
    light1: "",
    light2: "",
    light3: "",
    light5: "",
    light6: "",
    light7: "",
    primary: "#C4C1AD",
    secondary: "",
    success: "",
    warning: "",
  },

  darkMode: {
    danger: "hsl(353, 78%, 47%)",
    dark1: "",
    dark2: "",
    dark3: "",
    dark4: "",
    light1: "",
    light2: "",
    light3: "",
    light5: "",
    light6: "",
    light7: "",
    primary: "#C4C1AD",
    secondary: "",
    success: "",
    warning: "",
  },
}
